gtex_bfile: '/work-zfs/abattle4/marios/annotations/1kG_plink/1000G_hg38_plink_merged'
request: 'output/requests/empty.txt'
enrichment_filters:
  active: (df.p_active > 0.9) & (df.pip > 0.2) & (df.alpha < 0.95)
  primary: df.index.isin(df.groupby(['gene']).p_active.idxmax()) & (df.p_active > 0.9) & (df.pip > 0.2) & (df.alpha < 0.95)
  secondary: (~df.index.isin(df.groupby(['gene']).p_active.idxmax())) & (df.p_active > 0.9) & (df.pip > 0.2) & (df.alpha < 0.95)
  top: (df.loc[:, 'rank']==0) & (df.p_active > 0.9) & (df.pip > 0.2) & (df.alpha < 0.95)
  top_eqtl: "df.index.isin(df.groupby('gene').pval_nominal.idxmin())"
  top_pip: "df.index.isin((df.groupby('gene').pip.idxmax().values))"
  top_snp: "df.index.isin(df.groupby('gene').apply(lambda x: ((x.effect / np.sqrt(x.effect_var))**2).idxmax()))"

